{{- if (include "user-service.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "user-service.fullname" . }}
type: Opaque
data:
  ConnectionStrings__DefaultConnection: U2VydmVyPXBvc3RncmVzcWw7RGF0YWJhc2U9VXNlclNlcnZpY2VEYjtVc2VyIElEPXVzZXJzZXJ2aWNlO3Bhc3N3b3JkPXBhc3N3b3JkOw==
{{- end }}