{
 "title": "User Application",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Create",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Create\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Create\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Create\"}[$__rate_interval])))\r\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Create\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Update",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Update\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Update\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Update\"}[$__rate_interval])))\r\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Update\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Get",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Get\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Get\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Get\"}[$__rate_interval])))\r\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le,action) (rate(http_request_duration_seconds_bucket{controller=\"User\", action=\"Get\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Create",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(http_request_duration_seconds_count{controller=\"User\", action=\"Create\"}[$__rate_interval]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Update",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(http_request_duration_seconds_count{controller=\"User\", action=\"Update\"}[$__rate_interval]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Get",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(http_request_duration_seconds_count{controller=\"User\", action=\"Get\"}[$__rate_interval]))",
     "legendFormat": "rps"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Create",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(http_request_duration_seconds_count{controller=\"User\", action=\"Create\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Update",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(http_request_duration_seconds_count{controller=\"User\", action=\"Update\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Get",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(http_request_duration_seconds_count{controller=\"User\", action=\"Get\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "500"
    }
   ]
  },
  { "title": "NGNIX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum by(le, exported_service) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"us-app-user-service\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, exported_service) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"us-app-user-service\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, exported_service) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"us-app-user-service\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, exported_service) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"us-app-user-service\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (exported_service) (rate(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"us-app-user-service\"}[$__rate_interval]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (exported_service) (rate(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"us-app-user-service\", status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "500"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "{{pod}}" }
   ]
  },
  { "title": "Database Stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_fetched{datname=\"UserServiceDb\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_returned{datname=\"UserServiceDb\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_inserted{datname=\"UserServiceDb\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_updated{datname=\"UserServiceDb\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(pg_stat_database_tup_deleted{datname=\"UserServiceDb\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{datname=\"UserServiceDb\"}[$__rate_interval])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{datname=\"UserServiceDb\"}[$__rate_interval])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{datname=\"UserServiceDb\"}[$__rate_interval])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{datname=\"UserServiceDb\"}[$__rate_interval])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  }
 ]
}